# Site settings
title: Sumim's day
SEOTitle: Sumim's day
header-img: img/home-bg.jpg
email: vivid8222@gmail.com
description: "Web"
keyword: "Web, Front-End, UI, UX, HTML, CSS, JavaScript, Sumim"
url: "https://sumim00.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    sumim00
#twitter_username:   huxpro
#facebook_username:  huxpro
linkedin_username:  jiyoung-lim-22257a163



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: https-sumim00-github-io

disqus-shortname: https-sumim00-github-io

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-125060664-1'            # Format: UA-xxxxxx-xx
ga_domain: sumim00.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "지루하게 선명하기보다는,<br>흐릿해도 흥미롭게."
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    # #     title: "Su",
    # #     href: "http://su.gallery/"
    # # },{
    #     title: "解旻的博客",
    #     href: "http://xieminis.me/"
    # }
]
